// data/alumni-data.ts
export const alumniList = [
  {
    name: "Shantanu Garg",
    college: "Graphic Era (Deemed to be University)",
    course: "B.Tech (C.S.E with AI)",
    passout: "2025",
    img: "/alumni/profilepic/shantanu.png",
    tags: ["System design", "Problem Solving"],
  },
  {
    name: "Naman Khedwal",
    college: "Graphic Era (Deemed to be University)",
    course: "B.Tech (C.S.E with AI/ML)",
    passout: "2025",
    img: "/alumni/profilepic/naman.jpg",
    tags: ["ML", "Problem Solving"],
  },
  {
    name: "Ayush Sharma",
    college: "Graphic Era (Deemed to be University)",
    course: "B.Tech (C.S.E)",
    passout: "2025",
    img: "",
    tags: ["Narrator", "Marketing"],
  },
  {
    name: "Deepanshu Dangre",
    college: "Bharati Vidyapeeth college of engg.",
    course: "B.Tech (E.C.E with C.S.E)",
    passout: "2024",
    img: "/alumni/profilepic/deepanshu.png",
    tags: ["Management", "Blockchain"],
  },
  {
    name: "Farha Ansari",
    college: "2500+ successful counseling done",
    course: "Senior Career Counsellor",
    passout: "",
    img: "/alumni/profilepic/farhaansari.jpg",
  },
  {
    name: "Parnika Ingole",
    college: "Shri Guru Gobind Singhji Institute of Engineering and Technology, Nanded",
    course: "B.Tech (C.S.E)",
    passout: "2024",
    img: "/alumni/profilepic/parnika.jpg",
    tags: ["Design", "UI/UX"],
  },
  {
    name: "Yash Ahuja",
    college: "Indian Institute of Technology, Roorkee",
    course: "B.Tech (E.P)",
    passout: "2023",
    img: "",
  },
  {
    name: "Ishika Jain",
    college: "Shri Guru Gobind Singh College of Commerce",
    course: "Bcom",
    passout: "2025",
    img: "/alumni/profilepic/ishika.jpg",
    tags: ["HR", "Management"],
  },
  {
    name: "Ujjwal Jindal",
    college: "Maharaja Agrasen Institute of Technology, Delhi",
    course: "B.Tech (C.S.E)",
    passout: "2023",
    img: "/alumni/profilepic/ujjwal.png",
  },
  {
    name: "Vatsal Singh",
    college: "Delhi Technological University",
    course: "B.Des",
    passout: "2024",
    img: "/alumni/profilepic/vatsal.jpg",
  },
  {
    name: "Manvi Sharma",
    college: "Bhai Parmanand DSEU, Shakarpur Campus",
    course: "BBA BFSI",
    passout: "2025",
    img: "/alumni/profilepic/manvi.jpg",
  },
  {
    name: "Sujan Kotiyan",
    college: "Christ University, Bangalore",
    course: "BBA (hons.)",
    passout: "2025",
    img: "",
  },
];
